src/Entity/Prestataires.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PrestatairesRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: PrestatairesRepository::class)]
class Prestataires
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?string $Iban = null;

    #[ORM\Column]
    private ?bool $gardeDomicile = false;

    #[ORM\Column]
    private ?bool $vehicule = false;

    #[ORM\Column]
    private ?bool $jardin = false;

    #[ORM\Column(nullable: true)]
    private ?int $tarif = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $bio = null;

    #[ORM\ManyToMany(targetEntity: CategoriesAnimaux::class, inversedBy: 'prestataires')]
    private Collection $specialisations;

    #[ORM\OneToMany(mappedBy: 'prestataires', targetEntity: Indisponibilites::class)]
    private Collection $indisponibilite;

    #[ORM\OneToMany(mappedBy: 'prestataires', targetEntity: Commentaires::class, orphanRemoval: true)]
    private Collection $Commentaire;

    #[ORM\OneToMany(mappedBy: 'prestataires', targetEntity: SignalementAbus::class)]
    private Collection $signalement;

    #[ORM\OneToMany(mappedBy: 'prestataire', targetEntity: Images::class)]
    private Collection $images;

    #[ORM\OneToMany(mappedBy: 'prestataire', targetEntity: Favoris::class, orphanRemoval: true)]
    private Collection $favoris;

    #[ORM\Column(nullable: true)]
    private ?bool $soins_veto = null;

    #[ORM\Column(nullable: true)]
    private ?int $zoneGardiennage = null;

    #[ORM\Column(nullable: true)]
    private ?int $tarif_deplacement = null;

    #[ORM\OneToOne(mappedBy: 'prestataire', cascade: ['persist', 'remove'])]
    private ?Utilisateurs $utilisateur = null;

    #[ORM\OneToMany(mappedBy: 'gallerieGardien', targetEntity: Images::class)]
    private Collection $imgGallerie;

    #[ORM\OneToMany(mappedBy: 'gardien', targetEntity: NotesGardien::class, orphanRemoval: true)]
    private Collection $notesGardiens;

    #[ORM\OneToMany(mappedBy: 'gardien', targetEntity: Reservation::class)]
    private Collection $reservations;

    #[ORM\Column(nullable: true)]
    private ?int $tarif_promenade = null;

    #[ORM\Column(nullable: true)]
    private ?string $stripeAccountId = null;

    public function __construct()
    {
        $this->specialisations = new ArrayCollection();
        $this->indisponibilite = new ArrayCollection();
        $this->Commentaire = new ArrayCollection();
        $this->signalement = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->favoris = new ArrayCollection();
        $this->imgGallerie = new ArrayCollection();
        $this->notesGardiens = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIban(): ?string
    {
        return $this->Iban;
    }

    public function setIban(?string $Iban): self
    {
        $this->Iban = $Iban;

        return $this;
    }

    public function isGardeDomicile(): ?bool
    {
        return $this->gardeDomicile;
    }

    public function setGardeDomicile(bool $gardeDomicile): self
    {
        $this->gardeDomicile = $gardeDomicile;

        return $this;
    }

    public function isVehicule(): ?bool
    {
        return $this->vehicule;
    }

    public function setVehicule(bool $vehicule): self
    {
        $this->vehicule = $vehicule;

        return $this;
    }

    public function isJardin(): ?bool
    {
        return $this->jardin;
    }

    public function setJardin(bool $jardin): self
    {
        $this->jardin = $jardin;

        return $this;
    }

    public function getTarif(): ?int
    {
        return $this->tarif;
    }

    public function setTarif(?int $tarif): self
    {
        $this->tarif = $tarif;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }


    /**
     * @return Collection<int, CategoriesAnimaux>
     */
    public function getSpecialisations(): Collection
    {
        return $this->specialisations;
    }

    public function addSpecialisation(CategoriesAnimaux $specialisation): self
    {
        if (!$this->specialisations->contains($specialisation)) {
            $this->specialisations->add($specialisation);
        }

        return $this;
    }

    public function removeSpecialisation(CategoriesAnimaux $specialisation): self
    {
        $this->specialisations->removeElement($specialisation);

        return $this;
    }

    /**
     * @return Collection<int, Indisponibilites>
     */
    public function getIndisponibilite(): Collection
    {
        return $this->indisponibilite;
    }

    public function addIndisponibilite(Indisponibilites $indisponibilite): self
    {
        if (!$this->indisponibilite->contains($indisponibilite)) {
            $this->indisponibilite->add($indisponibilite);
            $indisponibilite->setPrestataires($this);
        }

        return $this;
    }

    public function removeIndisponibilite(Indisponibilites $indisponibilite): self
    {
        if ($this->indisponibilite->removeElement($indisponibilite)) {
            // set the owning side to null (unless already changed)
            if ($indisponibilite->getPrestataires() === $this) {
                $indisponibilite->setPrestataires(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaires>
     */
    public function getCommentaire(): Collection
    {
        return $this->Commentaire;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->Commentaire->contains($commentaire)) {
            $this->Commentaire->add($commentaire);
            $commentaire->setPrestataires($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->Commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getPrestataires() === $this) {
                $commentaire->setPrestataires(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, SignalementAbus>
     */
    public function getSignalement(): Collection
    {
        return $this->signalement;
    }

    public function addSignalement(SignalementAbus $signalement): self
    {
        if (!$this->signalement->contains($signalement)) {
            $this->signalement->add($signalement);
            $signalement->setPrestataires($this);
        }

        return $this;
    }

    public function removeSignalement(SignalementAbus $signalement): self
    {
        if ($this->signalement->removeElement($signalement)) {
            // set the owning side to null (unless already changed)
            if ($signalement->getPrestataires() === $this) {
                $signalement->setPrestataires(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setPrestataire($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getPrestataire() === $this) {
                $image->setPrestataire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Favoris>
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(Favoris $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris->add($favori);
            $favori->setPrestataire($this);
        }

        return $this;
    }

    public function removeFavori(Favoris $favori): self
    {
        if ($this->favoris->removeElement($favori)) {
            // set the owning side to null (unless already changed)
            if ($favori->getPrestataire() === $this) {
                $favori->setPrestataire(null);
            }
        }

        return $this;
    }

    public function isSoinsVeto(): ?bool
    {
        return $this->soins_veto;
    }

    public function setSoinsVeto(?bool $soins_veto): self
    {
        $this->soins_veto = $soins_veto;

        return $this;
    }

    public function getZoneGardiennage(): ?int
    {
        return $this->zoneGardiennage;
    }

    public function setZoneGardiennage(?int $zoneGardiennage): self
    {
        $this->zoneGardiennage = $zoneGardiennage;

        return $this;
    }

    public function getTarifDeplacement(): ?int
    {
        return $this->tarif_deplacement;
    }

    public function setTarifDeplacement(?int $tarif_deplacement): self
    {
        $this->tarif_deplacement = $tarif_deplacement;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateurs
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateurs $utilisateur): self
    {
        // unset the owning side of the relation if necessary
        if ($utilisateur === null && $this->utilisateur !== null) {
            $this->utilisateur->setPrestataire(null);
        }

        // set the owning side of the relation if necessary

src/Form/MaitreType.php
<?php

namespace App\Form;

use App\Entity\Maitres;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

class MaitreType extends AbstractType
{

    // Injection du service TranslatorInterface afin de pouvoir traduire les labels
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('bio', null, [
                'label' => 'ma présentation',
                'label' => $this->translator->trans('Ma présentation', [], 'form'),
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Maitres::class,
        ]);
    }
}

src/Controller/MaitreController.php
<?php

namespace App\Controller;

use App\Entity\Maitres;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MaitreController extends AbstractController
{
    #[Route('/page_maitre/{id}', name: 'page_maitre')]
    /**
     * @Route("/maitre/{id}",name="maitre_page")
     */
    public function index($id, EntityManagerInterface $entityManagerInterface): Response
    {
        $repository = $entityManagerInterface->getRepository(Maitres::class);
        $maitre = $repository->find($id);

        return $this->render('maitre/page_maitre.html.twig', [
            'maitre' => $maitre,
        ]);
    }
}

templates/profil/maitre/ajout_animal.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Ajout animal{% endtrans %}{% endblock %}

{% block body %}

{# Affichage si l'Id du gardien authentifié correspond a la variable $id envoyée #}
{% if app.user.maitre.id == id %}
    <div class="container row">

        <div class="row">
            <h2 class="center third-color">{% trans %}Ajout d'un animal{% endtrans %}</h2>
        </div>

        {{ form_start(form) }}
        <div class="input-field">
            {{form_label(form.nom) }}
            {{form_widget(form.nom, {'attr': {'class': 'secondary-color validate '}}) }}
        </div>
        <div class="input-field">
            {{form_label(form.age) }}
            {{form_widget(form.age, {'attr': {'class': 'secondary-color validate '}}) }}
        </div>
        <div class="input-field">
            {{form_label(form.description) }}
            {{form_widget(form.description, {'attr': {'class': 'secondary-color validate '}}) }}
        </div>
        <div class="choice-field">
            {{form_label(form.categorieAnimal) }}
            {{form_widget(form.categorieAnimal, {'attr': {'class': 'secondary-color validate '}}) }}
        </div>
        <div class="input-field">
            {{form_label(form.poids) }}
            {{form_widget(form.poids, {'attr': {'class': 'secondary-color validate '}}) }}
        </div>
        <div class="input-field">
            {{form_label(form.antecedentsMedicaux) }}
            {{form_widget(form.antecedentsMedicaux, {'attr': {'class': 'secondary-color validate '}}) }}
        </div>
        <div class="input-field">
            {{form_label(form.sociabilite) }}
            {{form_widget(form.sociabilite, {'attr': {'class': 'secondary-color validate '}}) }}
        </div>

        <button type="submit" class="btn waves-effect waves-light">{% trans %}Enregistrer{% endtrans %}</button>
        {{ form_end(form) }}

    </div>

        <div class="row center">
            <a class="btn-flat brown-text" href="{{ path('profil_maitre', {id: app.user.maitre.id}) }}">{% trans %}retour profil{% endtrans %}</a>
        </div>
{% endif %}
{% endblock %}

templates/profil/maitre/ajout_photo_animal.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Photo de mon animal{% endtrans %}{% endblock %}

{% block body %}

{# Affichage si l'Id du gardien authentifié correspond a la variable $id envoyée #}
{% if app.user.maitre.id == id %}
  <div class="container">

    {{ form_start(form) }}
      <div class="file-field input-field">
          <div class="btn waves-effect waves-light">
          <span>Image</span>
          {{form_widget(form.imageFile,{attr: {'type': 'file'}})}}
          </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
      <div class="row center">
        {{ form_widget(form.enregistrer,{'attr': {'class': 'register-form-submit btn'}}) }}
      </div>
    {{ form_end(form) }}
    
  </div>
{% else %}
<p class="center red">{% trans %}Désolé, vous n'avez pas les droits pour visiter cette page{% endtrans %}</p>
{% endif %}

    <div class="row center">
        <a class="btn-flat brown-text" href="{{ path('profil_maitre', {id: app.user.maitre.id}) }}">{% trans %}retour profil{% endtrans %}</a>
    </div>
    
{% endblock %}

templates/profil/maitre/ajout_photo_carrousel.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Photo de mon animal{% endtrans %}{% endblock %}

{% block body %}

{# Affichage si l'Id du gardien authentifié correspond a la variable $id envoyée #}
{% if app.user.maitre.id == id %}
<div class="container">

    {# Regles pour les images (maximum d'images dans le carrousel) : #}
    {% if app.user.maitre.imgGallerieMaitre|length <= 6 %}
        {{ form_start(form) }}
        <div class="file-field input-field">
            <div class="btn waves-effect waves-light">
            <span>Choisir image</span>
            {{form_widget(form.imageFile,{attr: {'type': 'file'}})}}
            </div>
            <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
            </div>
        </div>
        <div class="row center">
            {{ form_widget(form.enregistrer,{'attr': {'class': 'register-form-submit btn'}}) }}
        </div>
        {{ form_end(form) }}
    {% else %}
    <p class="center red">{% trans %}Vous avez atteint le nombre maximum d'images autorisées{% endtrans %}</p>
	{% endif %}

    <div class="container row">
        {% if app.user.maitre.imgGallerieMaitre is not empty %}
            {% for img in app.user.maitre.imgGallerieMaitre %}
            <div class="col s2">
                <a href="{{ path ('supprimer_photo_carrousel', {id: app.user.maitre.id, image_id: img.id }) }}">Supprimer</a>
                <img class="responsive-img" src="{{ asset('img/uploads/' ~ img.image) }}" alt="photo carrousel"/>
            </div>
            {% endfor %}
        {% endif %}
    </div>
    {% else %}
    <p class="center red">{% trans %}Désolé, vous n'avez pas les droits pour visiter cette page{% endtrans %}</p>
    {% endif %}
</div>

    <div class="row center">
        <a class="btn-flat brown-text" href="{{ path('profil_maitre', {id: app.user.maitre.id}) }}">{% trans %}retour profil{% endtrans %}</a>
    </div>
    
    
{% endblock %}

templates/profil/maitre/favoris.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Mes favoris{% endtrans %}{% endblock %}

{% block titreh1 %}
Mes gardiens favoris
{% endblock %}

{% block body %}

{% if app.user == maitre.utilisateur %}
  <div class="container">
    {% if pagination %}
    <div class="row">
        {% for fav in pagination %}
        <div class="col s6 m4 l3">
            <a href="{{ path('detail_gardien',{id: fav.prestataire.id}) }}">
            <div class="custom-card">

                <div class="custom-card-image">
                
                {% if fav.prestataire.images[0] is defined and fav.prestataire.images[0].image != '' %}
                    <img src="{{ asset('img/uploads/') ~ fav.prestataire.images[0].image }}" alt="photo de profil du gardien">
                    {% else %}
                    <img src="{{ asset('img/avatars/blank_profile.webp') }}" alt="photo de profil vide">
                {% endif %}
                </div>
                <div class="custom-card-content">
                {% if fav.prestataire.utilisateur.pseudo is defined %}
                <span class="card-title brown lighten-5 secondary-color">{{fav.prestataire.utilisateur.pseudo|capitalize  }}</span>

                <div class="divider brown lighten-3"></div>
                {% else %}
                <span class="card-title secondary-color">{{fav.prestataire.utilisateur.prenom}} {{fav.prestataire.utilisateur.nom|slice(0, 1)}}.</span>
                {% endif %}
                {% if fav.prestataire.utilisateur.adresse.commune %}
                <span class="card-title brown-text text-ligthen-3">{{fav.prestataire.utilisateur.adresse.commune}}</span>  
                {% endif %}
            </a>
                <div class="third-color">
                    <ul class="row">

                    {% if fav.prestataire.specialisations is not empty %}
                    <ul class="collapsible collapsible-custom text-white">
                    <li>
                        <div class="collapsible-header">{% trans %}Catégories animaux{% endtrans %}</div>
                        <div class="collapsible-body">
                        {% for specialisation in fav.prestataire.specialisations %}
                        {% if specialisation.nom == "Chats" %}
                            <i class="fa-solid fa-cat small text-white"></i>
                        {% elseif specialisation.nom == "Chiens" %}
                            <i class="fa-solid fa-dog small text-white"></i>
                        {% elseif specialisation.nom == "Reptiles" %}
                            <i class="fa-solid fa-worm small text-white"></i>
                        {% elseif specialisation.nom == "Arachnides" %}
                            <i class="fa-solid fa-spider v small text-white"></i>
                        {% elseif specialisation.nom == "Insectes" %}
                            <i class="fa-solid fa-locust small text-white"></i>
                        {% elseif specialisation.nom == "Poissons" %}
                            <i class="fa-solid fa-fish-fins small text-white"></i>
                        {% elseif specialisation.nom == "Amphibiens" %}
                            <i class="fa-solid fa-frog small text-white"></i>
                        {% elseif specialisation.nom == "Ruminants" %}
                            <i class="fa-solid fa-horse small text-white"></i>
                        {% elseif specialisation.nom == "Rongeurs" %}
                            <i class="fa-solid fa-carrot small text-white"></i>
                        {% elseif specialisation.nom == "Oiseaux" %}
                            <i class="fa-solid fa-kiwi-bird v small text-white"></i>
                        {% else %}
                            <i class="fa-solid fa-paw small text-white"></i>
                        {% endif %}
                        <p>{{specialisation.nom }}</p>
                        {% endfor %}
                    </li>
                    </ul>              
                    {% else %}
                    <p class="brown-text text-lighten-3">{% trans %}Aucune catégorie d'animal{% endtrans %}</p>
                    {% endif %}

                    {% if fav.prestataire.soinsVeto or fav.prestataire.gardeDomicile or fav.prestataire.jardin or fav.prestataire.vehicule %}
                    <ul class="collapsible collapsible-custom text-white">
                        <li>
                        <div class="collapsible-header">{% trans %}Compétences{% endtrans %}</div>
                        <div class="collapsible-body">
                            {% if fav.prestataire.gardeDomicile %}
                            <i class="fa-solid fa-house small text-white"></i>
                            <p>{% trans %}Hebergement{% endtrans %}</p>
                            {% endif %}
                            {% if fav.prestataire.soinsVeto %}
                            <i class="fa-solid fa-syringe small text-white"></i>
                            <p>{% trans %}Soins{% endtrans %}</p>
                            {% endif %}
                            {% if fav.prestataire.jardin %}
                            <i class="fa-solid fa-leaf small text-white"></i>
                            <p>{% trans %}Jardin{% endtrans %}</p>
                            {% endif %}
                            {% if fav.prestataire.vehicule %}
                            <i class="fa-solid fa-car small text-white"></i>
                            <p>{% trans %}Véhicule{% endtrans %}</p>
                            {% endif %}
                        <li>
                    </ul>
                    {% endif %}
                </div>
                </div>
            </div>
        </div> 
        {% endfor %}
        {% else %}
        <div class="col s12">
            <p>{% trans %}Aucun gardien trouvé{% endtrans %}</p>
        </div>
        {% endif %}
  </div>

    {# display navigation #}
    <div class="main-pagination">
            {{ knp_pagination_render(pagination) }}
    </div>
{% endif %}
    <div class="row center">
        <a class="btn-flat brown-text" href="{{ path('profil_maitre', {id: app.user.maitre.id}) }}">{% trans %}retour profil{% endtrans %}</a>
    </div>
    
{% endblock %}

templates/profil/maitre/imageProfil.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Ma photo de profil{% endtrans %}{% endblock %}

{% block body %}

{# Affichage si l'Id du gardien authentifié correspond a la variable $id envoyée #}
{% if app.user.maitre.id == id %}
  <div class="container">

    <div class="row">
        <h2 class="center third-color">{% trans %}Modification de ma photo{% endtrans %}</h2>
    </div>

    {{ form_start(form) }}
      <div class="file-field input-field">
        <div class="btn waves-effect waves-light">
          <span>Image</span>
          {{form_widget(form.imageFile,{attr: {'type': 'file'}})}}
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
      <div class="row center">
        {{ form_widget(form.enregistrer,{'attr': {'class': 'register-form-submit btn'}}) }}
      </div>
    {{ form_end(form) }}
    
  </div>
{% else %}
<p class="center red">{% trans %}Désolé, vous n'avez pas les droits pour visiter cette page de profil{% endtrans %}</p>
{% endif %}

    <div class="row center">
        <a class="btn-flat brown-text" href="{{ path('profil_maitre', {id: app.user.maitre.id}) }}">{% trans %}retour profil{% endtrans %}</a>
    </div>
    
{% endblock %}

templates/profil/maitre/modifier_infos_animal.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Informations animal{% endtrans %}{% endblock %}

{% block body %}

<div class="container row">

    <div class="row">
        <h2 class="center third-color">{% trans %}Modification des informations de votre animal{% endtrans %}</h2>
    </div>

    {{ form_start(form) }}
    <div class="input-field">
        {{form_label(form.nom) }}
        {{form_widget(form.nom, {'attr': {'class': 'secondary-color validate '}}) }}
    </div>
    <div class="input-field">
        {{form_label(form.age) }}
        {{form_widget(form.age, {'attr': {'class': 'secondary-color validate '}}) }}
    </div>
    <div class="input-field">
        {{form_label(form.description) }}
        {{form_widget(form.description, {'attr': {'class': 'secondary-color validate '}}) }}
    </div>
    <div class="choice-field">
        {{form_label(form.categorieAnimal) }}
        {{form_widget(form.categorieAnimal, {'attr': {'class': 'secondary-color validate '}}) }}
    </div>
    <div class="input-field">
        {{form_label(form.poids) }}
        {{form_widget(form.poids, {'attr': {'class': 'secondary-color validate '}}) }}
    </div>
    <div class="input-field">
        {{form_label(form.antecedentsMedicaux) }}
        {{form_widget(form.antecedentsMedicaux, {'attr': {'class': 'secondary-color validate '}}) }}
    </div>
    <div class="input-field">
        {{form_label(form.sociabilite) }}
        {{form_widget(form.sociabilite, {'attr': {'class': 'secondary-color validate '}}) }}
    </div>

    <button type="submit" class="btn waves-effect waves-light">{% trans %}Enregistrer{% endtrans %}</button>
    {{ form_end(form) }}

</div>

    <div class="row center">
        <a class="btn-flat brown-text" href="{{ path('profil_maitre', {id: app.user.maitre.id}) }}">{% trans %}retour profil{% endtrans %}</a>
    </div>
    
{% endblock %}

templates/profil/maitre/modifier_pseudo.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block titreh1 %}
    {% trans %} Modifier mon pseudo {% endtrans %}
{% endblock %}

{% block body %}

<div class="container">
    {{ form_start(form) }}

    <div class="input-field">
        {{ form_label(form.pseudo)}}
        {{ form_widget(form.pseudo, {'attr': {'class': 'secondary-color validate'}})}}
    </div>

    {{ form_end(form) }}
</div>

{% endblock %}

templates/profil/maitre/updateAdress.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Adresse maitre{% endtrans %}{% endblock %}

{% block body %}
{# Affichage si l'utilisateur connecté est bien le propriétaire du profil #}
{% if app.user == user %}
    <div class="container">

        <h2>{% trans %}Modification de mon adresse{% endtrans %}</h2>

            <div class="col s12 m6 l6">
            {{ form_start(form) }}
            <div class="input-field">
                {{ form_label(form.rue)}}
                {{ form_widget(form.rue, {'attr': {'class': 'secondary-color validate'}})}}
            </div>
            <div class="input-field">
                {{ form_label(form.numero) }}
                {{ form_widget(form.numero, {'attr': {'class': 'secondary-color validate'}}) }}
            </div>
            <div class="choice-field">
                {{ form_label(form.commune) }}
                {{ form_widget(form.commune, {'attr': {'class': 'secondary-color validate'}}) }}
            </div>
            <div class="choice-field">
                {{ form_label(form.codePostal) }}
                {{ form_widget(form.codePostal, {'attr': {'class': 'secondary-color validate'}}) }}
            </div>

            <button type="submit" class="btn waves-effect waves-light">Enregistrer</button>
            {{ form_end(form) }}
        </div>

    </div>
{% else %}
<p class="center red">{% trans %}Désolé, vous n'avez pas les droits pour visiter cette page de profil{% endtrans %}</p>
{% endif %}
    <div class="row center">
        <a class="btn-flat brown-text" href="{{path('profil_maitre',{id: app.user.maitre.id})}}">{% trans %}retour profil{% endtrans %}</a>
    </div>
{% endblock %}

templates/profil/maitre/updateInfos.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Gestions infos gardien{% endtrans %}{% endblock %}

{% block body %}

{% if app.user == maitre.utilisateur %}
    <div class="container">

        <div class="row">
            <h2 class="center third-color">{% trans %}Modification de ma présentation{% endtrans %}</h2>
        </div>

        <div class="col s12 m6 l6">
            {{ form_start(form) }}
            <div class="input-field">
                {{ form_widget(form.bio, {'attr': {'class': 'materialize-textarea secondary-color validate'}})}}
            </div>
    
            <button type="submit" class="btn">{% trans %}Enregistrer{% endtrans %}</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endif %}

    <div class="row center">
        <a class="btn-flat brown-text" href="{{ path('profil_maitre', {id: app.user.maitre.id}) }}">{% trans %}retour profil{% endtrans %}</a>
    </div>
    

{% endblock %}