src/Entity/Newsletters.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\NewslettersRepository;

#[ORM\Entity(repositoryClass: NewslettersRepository::class)]
class Newsletters
{

    function __construct()
    {
        // initialisation de la date de création à la date du jour
        $this->dateCreation = new DateTime();
        $this->is_sent = false;
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $contenu = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column]
    private ?bool $is_sent = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateEnvoi = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function isIsSent(): ?bool
    {
        return $this->is_sent;
    }

    public function setIsSent(bool $is_sent): self
    {
        $this->is_sent = $is_sent;

        return $this;
    }

    public function getDateEnvoi(): ?\DateTimeInterface
    {
        return $this->dateEnvoi;
    }

    public function setDateEnvoi(?\DateTimeInterface $dateEnvoi): self
    {
        $this->dateEnvoi = $dateEnvoi;

        return $this;
    }
}

src/Form/NewslettersType.php
<?php

namespace App\Form;

use App\Entity\Newsletters;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class NewslettersType extends AbstractType
{

    // Injection du service TranslatorInterface afin de pouvoir traduire les labels
    private $translator;

    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }
    
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', null, [
                'label' => 'Titre',
                'label' => $this->translator->trans('Titre', [], 'form'),
            ])
            ->add('contenu',null,[
                'label' => $this->translator->trans('Contenu', [], 'form'),
            ])
            ->add('enregistrer', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-primary'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Newsletters::class,
        ]);
    }
}

src/Controller/AdminCrudController.php
<?php

namespace App\Controller;

use App\Entity\Images;
use App\Form\ImageType;
use App\services\UploaderHelper;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdminCrudController extends AbstractController
{

    // -----------------------------------------------
    // Gestion des photos du carrousel page d'accueil
    // -----------------------------------------------
    /**
     * @Route("/carrousel", name="admin_carrousel")
     */
    public function CrudCarrousel(EntityManagerInterface $entityManager, UploaderHelper $uploaderHelper, Request $request, TranslatorInterface $translator): Response
    {
        $repository = $entityManager->getRepository(Images::class);
        $carrouselImages = $repository->findBy(['homeCarrousel' => 1]);
        // comtpage et stockage du nombre de photos du carrousel présent en DB
        $carrouselCount = $repository->findBy(['homeCarrousel' => 1]);
        $carrouselCount = count($carrouselCount);


        // création du formulaire
        $imgCarrousel = new Images();
        $form = $this->createForm(ImageType::class, $imgCarrousel);
        $form->handleRequest($request);
  
  
         if ($form->isSubmitted() && $form->isValid()) {
  
          $uploadedImage = $form['imageFile']->getData();
  
          if($uploadedImage){
            $newImageName = $uploaderHelper->uploadImages($uploadedImage);
  
            $imgCarrousel->setImage($newImageName);
            $imgCarrousel->setHomeCarrousel(true);
          }
  
          if ($imgCarrousel->getImage() != null ){
            $entityManager->persist($imgCarrousel);
            $entityManager->flush();
  
            $msg = $translator->trans('Votre photo a bien été ajoutée');
            $this->addFlash('success', $msg);
  
            return $this->redirectToRoute('admin_carrousel', [
            ]);
          }
          
          $msg = $translator->trans('Votre image n\'est pas valide');
          $this->addFlash('notice', $msg);
         }
  
        return $this->render('admin_crud/carrousel/carrousel.html.twig', [
            'form' => $form->createView(),
            'carrouselCount' => $carrouselCount,
            'carrouselImages' => $carrouselImages,
        ]);

    }


    // -------------------------------------
    // Supprimer une photo du carrousel
    // -------------------------------------
    /**
     * @Route("/admin/supprimer_image_carrousel/{id}", name="admin_suppr_carrousel")
     */
    public function supprimerPhotoCarrouselAccueil($id, EntityManagerInterface $entityManager, UploaderHelper $uploaderHelper, TranslatorInterface $translator): Response
    {
      
      $repositoryImage = $entityManager->getRepository(Images::class);
      $image = $repositoryImage->find($id);

      $imageToDelete = $image->getImage();

      $entityManager->remove($image);
      $entityManager->flush();

      // suppression du fichier dans le dossier uploads
      $imgToDelete = $uploaderHelper->getUploadPath().'/'.$imageToDelete;
      unlink($imgToDelete);

      $msg = $translator->trans('Votre photo a bien été supprimée');
      $this->addFlash('success', $msg);

      return $this->redirectToRoute('admin_carrousel', [
      ]);
    }

}

src/Controller/NewsletterController.php
<?php

namespace App\Controller;

use App\Entity\Maitres;
use App\Entity\Newsletters;
use App\Form\NewslettersType;
use Symfony\Component\Mime\Email;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Message\SendNewsletterEmail;

class NewsletterController extends AbstractController
{

    // voir les newsletters
    /**
     * @Route("/newsletters", name="newsletters")
     */
    public function index(EntityManagerInterface $entityManagerInterface): Response
    {
        $repository = $entityManagerInterface->getRepository(Newsletters::class);
        $newsletters = $repository->findAll();

        return $this->render('admin_crud/newsletters/newsletters.html.twig', [
            'newsletters' => $newsletters,
        ]);

    }

    // detail newsletter
    /**
     * @Route("/newsletters/{id}", name="detail_newsletter")
     */
    public function newsletter(EntityManagerInterface $entityManagerInterface, $id): Response
    {
        $repository = $entityManagerInterface->getRepository(Newsletters::class);
        $newsletter = $repository->find($id);

        return $this->render('admin_crud/newsletters/detail.html.twig', [
            'newsletter' => $newsletter,
        ]);

    }

    // envoi newsletter par email a tous les maitres abonnés
    /**
     * @Route("/newsletters/{id}/envoyer", name="envoyer_newsletter")
     */
    public function envoyerNewsletter($id, EntityManagerInterface $entityManager, MailerInterface $mailer, TranslatorInterface $translator):Response
    {
        $repository = $entityManager->getRepository(Newsletters::class);
        $newsletter = $repository->find($id);

        // récupérer tous les maitres abonnés à la newsletter
        $repository = $entityManager->getRepository(Maitres::class);
        $maitres = $repository->findBy(['newsletter' => true]);

        foreach ($maitres as $maitre) {
            $email = $maitre->getUtilisateur()->getEmail();

            // envoi d'un mail récapitulatif au prestataire
            $email = (new Email())
                ->from('newsletter@gardien2pattes.be')
                ->to($email)
                ->subject($newsletter->getNom())
                ->html($this->renderView('emails/newsletter.html.twig', [
                    'newsletter' => $newsletter,
                    'maitre' => $maitre
                ]));

            $mailer->send($email);
        }

        $msg = $translator->trans('Newsletter envoyée avec succès !');
        $this->addFlash('success',$msg);

        return $this->redirectToRoute('newsletters');
    }



    //creer nouvelle newsletter
    /**
     * @Route("/newsletter_nouvelle", name="nouvelle_newsletter")
     */
    public function creerNewsletter(EntityManagerInterface $entityManagerInterface, Request $request, TranslatorInterface $translator): Response
    {
        $form = $this->createForm(NewslettersType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $newsletter = new Newsletters();
            $newsletter->setContenu($form->get('contenu')->getData());
            $newsletter->setNom($form->get('nom')->getData());
            $newsletter->isIsSent(false);

            $entityManagerInterface->persist($newsletter);
            $entityManagerInterface->flush();

            $msg = $translator->trans('Newsletter créée avec succès !');
            $this->addFlash('success',$msg);

            return $this->redirectToRoute('newsletters');
        }
    
        return $this->render('admin_crud/newsletters/new_newsletter.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    //modifier newsletter
    /**
     * @Route("/newsletters/{id}/modifier", name="modifier_newsletter")
     */
    public function modifierNewsletter(EntityManagerInterface $entityManagerInterface,Request $request, $id): Response
    {
        $repository = $entityManagerInterface->getRepository(Newsletters::class);
        $newsletter = $repository->find($id);

        $form = $this->createForm(NewslettersType::class, $newsletter);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $newsletter = $form->getData();
            
            $entityManagerInterface->persist($newsletter);
            $entityManagerInterface->flush();

            $this->addFlash('success', 'Newsletter modifiée avec succès !');

            return $this->redirectToRoute('detail_newsletter', 
            ['id' => $newsletter->getId()
            ]);
        }
    
        return $this->render('admin_crud/newsletters/modifier.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    //suppirmer une newsletter
    /**
     * @Route("/newsletters/{id}/supprimer", name="supprimer_newsletter")
     */
    public function supprimerNewsletter(EntityManagerInterface $entityManagerInterface, $id): Response
    {
        $repository = $entityManagerInterface->getRepository(Newsletters::class);
        $newsletter = $repository->find($id);

        $entityManagerInterface->remove($newsletter);
        $entityManagerInterface->flush();

        $this->addFlash('success', 'Newsletter supprimée avec succès !');
        return $this->redirectToRoute('newsletters');
    }


    // se desabonner de la newsletter (via lien dans email)
    /**
     * @Route("/desabonnement_newsletter/{id}", name="desabonnement_newsletter")
     */
    public function desabonnerNewsletter($id, EntityManagerInterface $entityManagerInterface): Response
    {
        $repository = $entityManagerInterface->getRepository(Maitres::class);
        $maitre = $repository->find($id);

        $maitre->setNewsletter(false);
        $entityManagerInterface->persist($maitre);
        $entityManagerInterface->flush();

        $this->addFlash('success', 'Vous êtes désabonné de la newsletter !');
        return $this->redirectToRoute('home');
    }

}

templates/admin_crud/newsletters/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail newsletter{% endblock %}

{% block titreh1 %}
    Detail de la newsletter
{% endblock %}


{% block body %}
<div class="container">

    {% if newsletter.isSent == false %}
        <div class='admin-detail-newsletter'>
            <div>
                <h2>{{ newsletter.nom}}</h2>
                <p>{{ newsletter.contenu}}</p>
                <p>Date de création: {{ newsletter.dateCreation|date('d/m/Y')}}</p>
            </div>
            <div class='admin-detail-newsletter-links'>
                <a href="{{path('modifier_newsletter', {id:newsletter.id}) }}">Modifier</a>
                <a href="{{path('supprimer_newsletter', {id:newsletter.id}) }}">Supprimer</a>
                <a href="{{path('envoyer_newsletter', {id:newsletter.id}) }}">Envoyer</a>
            </div>
        </div>
        {% else %}
            <div class='admin-detail-newsletter'>
                <h2>Titre: {{ newsletter.nom}}</h2>
                <p>Contenu: {{ newsletter.contenu}}</p>
                <p>Date de création: {{ newsletter.dateCreation|date('d/m/Y')}}</p>
                <p>Envoyée le {{newsletter.dateEnvoi|date('d/m/Y') }}</p>
            </div>
        </div>
    {% endif %}

    <div class='admin-detail-newsletter-back-button'>
        <a href="{{path('newsletters') }}">retour liste newsletters</a>
    </div>
</div>
{% endblock %}

templates/admin_crud/newsletters/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail newsletter{% endblock %}

{% block titreh1 %}
    Modifier la newsletter
{% endblock %}

{% block body %}

<div class="container">
    {{ form_start(form) }}
        <div class="input-field">
            {{ form_label(form.nom) }}
            {{ form_widget(form.nom, {'attr': {'class': 'secondary-color validate'}}) }}
        </div>
        <div class="input-field">
            {{ form_label(form.contenu) }}
            {{ form_widget(form.contenu, {'attr': {'class': 'secondary-color validate'}}) }}
        </div>
    {{ form_end(form) }}

    <div class='admin-detail-newsletter-back-button'>
        <a href="{{path('newsletters') }}">retour liste newsletters</a>
    </div>
</div>

{% endblock %}

templates/admin_crud/newsletters/new_newsletter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle newsletter{% endblock %}

{% block titreh1 %}
    Nouvelle newsletter
{% endblock %}

{% block body %}

    <div class="container">
        {{ form_start(form) }}
            <div class="input-field">
                {{ form_label(form.nom) }}
                {{ form_widget(form.nom, {'attr': {'class': 'secondary-color validate'}}) }}
            </div>
            <div class="input-field">
                {{ form_label(form.contenu) }}
                {{ form_widget(form.contenu, {'attr': {'class': 'secondary-color validate'}}) }}
            </div>
        {{ form_end(form) }}
    </div>
    <div class="admin-detail-newsletter-back-button">
        <a href="{{path('newsletters') }}">retour liste newsletters</a>
    </div>

{% endblock %}

templates/admin_crud/newsletters/newsletters.html.twig
{% extends 'base.html.twig' %}

{% block title %}Newsletters{% endblock %}

{% block titreh1 %}Admin Newsletters{% endblock %}

{% block body %}
<div class="container">

    <p class='center'><a class='btn' href="{{path('nouvelle_newsletter') }}">Créer une newsletter</a></p>

    <div class="admin-newsletters">
        <h2 class=''>Liste des neswletters:</h2>
        <ul>
            {% for n in newsletters %}
            {% if n.isSent %}
                <li><a href="{{path('detail_newsletter', {id:n.id}) }}">{{n.nom }}</a>
                <p>Envoyée le {{n.dateEnvoi|date('d/m/Y') }}</p>
                </li>
                {% else %}
                <li><a href="{{path('detail_newsletter', {id:n.id}) }}">{{n.nom }}</a>
                <p>Pas encore envoyée</p>
                </li>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
    
    <div class='admin-detail-newsletter-back-button'>
        <a href="{{path('admin') }}">Retour tableau de bord admin</a>
    </div>
</div>
{% endblock %}